# Note: because CodeBuild is not enabled for AWS educate accounts, this file has been abandoned.
version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y apache2

# UNIT TEST?